//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cesi.ProjetDominante.Client {
	
	
	public partial class Decypher {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.FileUpload FileUpload1;
		
		protected System.Web.UI.WebControls.FileUpload FileUpload2;
		
		protected System.Web.UI.WebControls.FileUpload FileUpload3;
		
		protected System.Web.UI.WebControls.FileUpload FileUpload4;
		
		protected System.Web.UI.WebControls.FileUpload FileUpload5;
		
		protected System.Web.UI.WebControls.Button UploadButton;
		
		protected System.Web.UI.WebControls.Label UploadStatusLabel;
	}
}
